trustpilot/plugin-magento2

Block/Success.php
Helper/Data.php
Helper/HttpClient.php
Helper/OrderData.php
Helper/TrustpilotHttpClient.php
Observer/ConfigObserver.php
Observer/OrderSaveObserver.php
composer.json
etc/adminhtml/events.xml
etc/config.xml
etc/events.xml

Order_from_backend

---

etc/config.xml

Trustbox_functionality

---

Block/System/Config/Preview.php
Helper/Data.php
composer.json
etc/config.xml

Scope default value fix

---

Block/Trustbox.php
Helper/OrderData.php
composer.json
etc/config.xml

Update to 1.0.230

---

Model/Config.php
composer.json

Integrationapp

---

Block/Success.php
Block/System/Config/Admin.php
Block/Trustbox.php
Block/Trustpilot.php
Controller/Adminhtml/Index/Index.php
Helper/Data.php
Helper/OrderData.php
Helper/Products.php
Model/Config.php
composer.json
view/adminhtml/templates/system/config/admin.phtml
view/adminhtml/web/js/admin.js

Sku_improvements

---

Model/Config.php
composer.json
view/adminhtml/layout/default.xml
view/adminhtml/web/css/trustpilot.min.css
view/adminhtml/web/js/admin.min.js
view/frontend/layout/default.xml
view/frontend/web/css/trustpilot.min.css

Add minified files

---

Block/Head.php
Block/System/Config/Admin.php
Block/Trustbox.php
Block/Trustpilot.php
Controller/Adminhtml/Index/Index.php
Helper/Data.php
Helper/PastOrders.php
Model/Config.php
composer.json
view/adminhtml/templates/system/config/admin.phtml

Use storeid from param

---

Block/Head.php
Block/Success.php
Block/System/Config/Admin.php
Block/Trustpilot.php
Controller/Adminhtml/Index/Index.php
Helper/Data.php
Helper/OrderData.php
Helper/PastOrders.php
Model/Config.php
Observer/OrderSaveObserver.php
composer.json
view/adminhtml/templates/system/config/admin.phtml

Scope param

---

Block/System/Config/Admin.php
Block/Trustbox.php
Block/Trustpilot.php
Helper/Data.php
Model/Config.php
composer.json
view/adminhtml/templates/system/config/admin.phtml

Fix scope storeid incosistencies

---

Block/Trustpilot.php
Model/Config.php
composer.json
view/adminhtml/web/js/admin.js
view/adminhtml/web/js/admin.min.js

Safer messages handling

---

Helper/Data.php
Model/Config.php
composer.json
view/adminhtml/templates/system/config/admin.phtml
view/adminhtml/web/js/admin.js

Sentry error fixes

---

Block/Success.php
Block/System/Config/Admin.php
Block/Trustpilot.php
Helper/Data.php
Helper/OrderData.php
Helper/TrustpilotHttpClient.php
Helper/TrustpilotLog.php
Helper/TrustpilotPluginStatus.php
Model/Config.php
composer.json
view/adminhtml/templates/system/config/admin.phtml
view/adminhtml/web/js/admin.js
view/adminhtml/web/js/admin.min.js

Drag and drop fix

---

Model/Config.php
composer.json
view/adminhtml/web/js/admin.js
view/frontend/templates/head/head.phtml

Try parse message before handling

---

Model/Config.php
composer.json

Bump up version

---

Helper/TrustpilotHttpClient.php

This is causing an 'Array to string conversion' on HttpClient.php:57

Data passed as incorrect argument to post function

---

Model/Config.php

Version 2.6.542

---

Helper/Data.php
Helper/OrderData.php
Model/Config.php
composer.json

New release

---

etc/acl.xml

Add the acl.xml to allow/disallow who can access truspilot menu !

Add acl to manage who access truspilot menu !

---

Helper/Data.php
Model/Config.php
composer.json

Minor bug fixes and improvements

---

etc/csp_whitelist.xml

Csp whitelist

---

Model/Config.php
composer.json

Version bump

---

Block/Trustbox.php
Model/Config.php
composer.json

New version 2 6 564

---

Block/Success.php
Block/Trustbox.php
Helper/Data.php
Model/Config.php
composer.json

Bug fixes and improvements
